### ISSUE TITLE
Lions Club Sponsor Logo On Ipad landscape and portrait is elongated

### ISSUE THREAD

**Issue by ettienekorayyi** [codesydney/eisteddfod#113]
Lions Club Sponsor Logo On Ipad landscape and portrait is elongated and the name of the Lions Club runs across the logo.  However,  Sue has noted towards the bottom of the sponsorship page that all of the sponsors have been listed and the set out looks great.  Perhaps it is planned that that “footer” will appear on each page.  That will overcome the elongated logo issue.

**Comment by HDKHALILI** [comment]
The new layout for the sponsors has fixed the issue
