### ISSUE TITLE
Changes in sponsorship page

### ISSUE THREAD

**Issue by ettienekorayyi** [codesydney/eisteddfod#142]
Bronze:
- The client wanted to revert the minimum sponsorship level to $50.
- Replace the $25 minimum rate into $50 to $150

Gold:
- insert the link as per the bronze and silver.  The text would read:

 “In the Program,  …….  Plus your logo will appear on our Website as a Gold Sponsor in the “Our Current Sponsors” section.
It should look the same as the screenshot below:
![image](https://user-images.githubusercontent.com/19362078/150950037-572d2efa-d3bf-41ea-b7a1-3d8bd4bb68c4.png)

**Comment by HDKHALILI** [comment]
Made the changes to the text
