### ISSUE TITLE
The committee member aread doesn't have the same width as the rest of the page content

### ISSUE THREAD

**Issue by HDKHALILI** [codesydney/eisteddfod#63]
![ep-members-small-padding](https://user-images.githubusercontent.com/14176079/144766508-3a936229-fec1-4688-9985-9dcfa91ff2a4.png)

**Comment by ettienekorayyi** [comment]
Already fixed

Screenshot:
![image](https://user-images.githubusercontent.com/19362078/146625586-a9de6ad6-a3ab-4b76-9a04-4f8d01b7fcd9.png)
