### ISSUE TITLE
Testimonial Comments overlaps with other statements

### ISSUE THREAD

**Issue by ettienekorayyi** [codesydney/eisteddfod#94]
Screenshot:
![image](https://user-images.githubusercontent.com/19362078/145896450-235d7d9f-b78e-475e-8819-04e20805cac2.png)

**Comment by HDKHALILI** [comment]
An
![ep-testimonials](https://user-images.githubusercontent.com/14176079/145911053-82d660f5-d1f2-497b-b895-be57cf082b2c.png)
![ep-testimonials-2](https://user-images.githubusercontent.com/14176079/145911077-f382b7cf-980a-46dc-8a6c-ca3738206622.png)

d these too:
